# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 14:25
from __future__ import unicode_literals

import Pizza.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_id', models.CharField(max_length=50, verbose_name=Pizza.models.Pizza)),
                ('pizza_size', models.IntegerField(verbose_name=Pizza.models.Pizza)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_id', models.CharField(max_length=50)),
                ('pizza_size', models.IntegerField()),
            ],
        ),
    ]
