# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_auto_20181123_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='orders',
            field=models.ManyToManyField(related_name='orders', to='Pizza.Pizza'),
        ),
    ]
