# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0004_auto_20181123_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_size',
            field=models.IntegerField(),
        ),
    ]
