# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_auto_20181124_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='orders',
        ),
    ]
