# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_remove_customers_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
