# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0007_delete_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza_id',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_id',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Pizza.Pizza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
